refactor: Get the simpleExchange basically working
Agoric/dapp-simple-exchange pull request #12
Opened 2020-04-21 23:16 UTC by Chris-Hibbert

orderbook sometimes has no buy or no sell.

The brandRegKeys are coming out as 'Asset', and 'Price'. deal with
  that rather than fixing it.

2020-04-21 23:55 UTC, michaelfig requested changes
LGTM, modulo some confusing variable names.

2020-04-21 23:55 UTC, michaelfig commented on api/src/handler.js
> +    ({ extent, brandRegKey: brandToKeyword.get(brand) });
Please change this field into `keyword` instead of `brandRegKey`.

2020-04-21 23:55 UTC, michaelfig commented on ui/src/components/OrderBook.jsx
>                  .filter(({ Asset: { brandRegKey: AssetBrandRegKey }, Price: { brandRegKey: PriceBrandRegKey } }) =>
Here too, `brandRegKey` becomes `keyword`, `AssetKeyword` and `PriceKeyword`.

2020-04-22 00:26 UTC, katelynsills approved these changes
I'm still getting some errors, but this seems like a great improvement. I think we should merge and then fix the errors separately.

When I made orders and they get matched, they don't show up in the order history. Also, somehow the inclusion of one more order closed a bunch of them. 

<img width="1664" alt="Screen Shot 2020-04-21 at 5 20 25 PM" src="https://user-images.githubusercontent.com/2441069/79927615-2e958b00-83f5-11ea-82cb-f2bbafa852a8.png">

<img width="1667" alt="Screen Shot 2020-04-21 at 5 21 09 PM" src="https://user-images.githubusercontent.com/2441069/79927621-335a3f00-83f5-11ea-96dd-1aa413af21e8.png">


Also, I got this error in the `agoric start` terminal:
<img width="1260" alt="Screen Shot 2020-04-21 at 5 22 22 PM" src="https://user-images.githubusercontent.com/2441069/79927610-28071380-83f5-11ea-8435-731e2766a715.png">

2020-04-22 17:30 UTC, Chris-Hibbert commented
These changes have been incorporated into #9 directly. There were enough changes on different branches that this seemed the simplest way to get a reviewable PR.

2020-04-22 20:54 UTC, Chris-Hibbert commented
closed by #9

2020-04-22 20:54 UTC, closed without merging